CREATE TABLE titser (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50),
    lastname VARCHAR(50),
    YearsofExperience INT,
    favoriteSubject VARCHAR(50),
    email VARCHAR(100)
);

INSERT INTO titser (firstname, lastname, YearsofExperience, favoriteSubject, email) VALUES
('Alice', 'Smith', 5, 'Mathematics', 'alice.smith@example.com'),
('Bob', 'Johnson', 10, 'Physics', 'bob.johnson@example.com'),
('Carol', 'Williams', 7, 'Chemistry', 'carol.williams@example.com'),
('David', 'Brown', 3, 'Biology', 'david.brown@example.com'),
('Eva', 'Jones', 8, 'History', 'eva.jones@example.com'),
('Frank', 'Miller', 15, 'Geography', 'frank.miller@example.com'),
('Grace', 'Davis', 4, 'Art', 'grace.davis@example.com'),
('Henry', 'Garcia', 6, 'Music', 'henry.garcia@example.com'),
('Isabel', 'Martinez', 12, 'Literature', 'isabel.martinez@example.com'),
('Jack', 'Rodriguez', 9, 'Computer Science', 'jack.rodriguez@example.com'),
('Liam', 'Harris', 11, 'Mathematics', 'liam.harris@example.com'),
('Mia', 'Clark', 2, 'Science', 'mia.clark@example.com'),
('Noah', 'Lewis', 8, 'English', 'noah.lewis@example.com'),
('Olivia', 'Walker', 14, 'History', 'olivia.walker@example.com'),
('Patrick', 'Young', 5, 'Physical Education', 'patrick.young@example.com'),
('Quinn', 'Allen', 7, 'Drama', 'quinn.allen@example.com'),
('Rachel', 'King', 9, 'Music', 'rachel.king@example.com'),
('Samuel', 'Wright', 6, 'Art', 'samuel.wright@example.com'),
('Tara', 'Scott', 12, 'Computer Science', 'tara.scott@example.com'),
('Uma', 'Evans', 10, 'Geography', 'uma.evans@example.com'),
('Violet', 'Baker', 4, 'Physics', 'violet.baker@example.com'),
('William', 'Carter', 13, 'Mathematics', 'william.carter@example.com'),
('Xander', 'Foster', 1, 'Literature', 'xander.foster@example.com'),
('Yvonne', 'Griffin', 9, 'Chemistry', 'yvonne.griffin@example.com'),
('Zachary', 'Howard', 7, 'Biology', 'zachary.howard@example.com'),
('Amy', 'Hughes', 8, 'History', 'amy.hughes@example.com'),
('Brian', 'Jenkins', 11, 'Geography', 'brian.jenkins@example.com'),
('Chloe', 'Mitchell', 6, 'Art', 'chloe.mitchell@example.com'),
('Dylan', 'Perry', 10, 'Music', 'dylan.perry@example.com'),
('Emma', 'Reed', 3, 'Computer Science', 'emma.reed@example.com'),
('Fred', 'Sanchez', 5, 'Science', 'fred.sanchez@example.com'),
('Gina', 'Bell', 14, 'Mathematics', 'gina.bell@example.com'),
('Hank', 'Butler', 7, 'English', 'hank.butler@example.com'),
('Ivy', 'Cooper', 11, 'History', 'ivy.cooper@example.com'),
('Jake', 'Turner', 4, 'Physical Education', 'jake.turner@example.com'),
('Kate', 'Parker', 8, 'Drama', 'kate.parker@example.com'),
('Leo', 'Collins', 10, 'Music', 'leo.collins@example.com'),
('Mona', 'Edwards', 12, 'Art', 'mona.edwards@example.com'),
('Nina', 'Morgan', 9, 'Computer Science', 'nina.morgan@example.com'),
('Oscar', 'Ramos', 6, 'Geography', 'oscar.ramos@example.com');


